### ISSUE TITLE
Switching colorscheme gives me an error

### ISSUE THREAD

**Issue by apoorvparijat** [MvanDiemen/ghostbuster#1]
Any thoughts on this?

```
Error detected while processing /Users/apoorv/.vim/colors/ghostbuster.vim:
line  354:
E121: Undefined variable: s:trio_2
E116: Invalid arguments for function <SNR>12_X
```

**Comment by MvanDiemen** [comment]
Can you use `set background=dark`? The support for the light background is broken for now.

**Comment by MvanDiemen** [comment]
Just fixed the light colorscheme, could you try again with the newer version?

**Comment by MvanDiemen** [comment]
Got any updates?

**Comment by apoorvparijat** [comment]
Hadn't checked my mails. Will have a look today and updates.

**Comment by MvanDiemen** [comment]
Any updates?

**Comment by jim3** [comment]
How do I get your colorscheme to always give me the light version? I have set background=dark all the time. It initially gave me a light version but then switch to dark. Anything I can put in my .vimrc to fix it? Nice colorscheme, btw. :)
